version: '3'
services:
  zookeeper:
    image: confluentinc/cp-zookeeper:7.4.0
    platform: linux/arm64  # For Mac M1 compatibility
    container_name: zookeeper
    environment:
      ZOOKEEPER_CLIENT_PORT: 2181
      ZOOKEEPER_TICK_TIME: 2000
    ports:
      - "2181:2181"

  kafka:
    image: confluentinc/cp-kafka:7.4.0
    platform: linux/arm64  # For Mac M1 compatibility
    container_name: kafka
    depends_on:
      - zookeeper
    ports:
      - "9092:9092"
    environment:
      KAFKA_BROKER_ID: 1
      KAFKA_ZOOKEEPER_CONNECT: zookeeper:2181
      KAFKA_LISTENER_SECURITY_PROTOCOL_MAP: PLAINTEXT:PLAINTEXT,PLAINTEXT_HOST:PLAINTEXT
      KAFKA_ADVERTISED_LISTENERS: PLAINTEXT://kafka:29092,PLAINTEXT_HOST://localhost:9092
      KAFKA_INTER_BROKER_LISTENER_NAME: PLAINTEXT
      KAFKA_OFFSETS_TOPIC_REPLICATION_FACTOR: 1

  hbase:
    image: harisekhon/hbase:1.4
    platform: linux/amd64  # This image doesn't need platform specification as it works with emulation
    container_name: hbase
    ports:
      - "16000:16000"   # HBase Master
      - "16010:16010"   # HBase Master Web UI
      - "16020:16020"   # HBase Regionserver
      - "16030:16030"   # HBase Regionserver Web UI
      - "9090:9090"     # Thrift API
      - "8085:8085"     # REST API
    environment:
      - HBASE_MANAGES_ZK=false
      - HBASE_ZOOKEEPER_QUORUM=zookeeper
    depends_on:
      - zookeeper
    volumes:
      - hbase_data:/hbase-data

  mysql:
    image: arm64v8/mysql:8.0
    platform: linux/arm64  # For Mac M1 compatibility
    container_name: mysql
    ports:
      - "3306:3306"
    environment:
      MYSQL_ROOT_PASSWORD: rootpassword
      MYSQL_DATABASE: sentiment_analysis
      MYSQL_USER: user
      MYSQL_PASSWORD: password
    volumes:
      - mysql_data:/var/lib/mysql

volumes:
  hbase_data:
    driver: local
  mysql_data:
    driver: local